version: "3.9"

services:
  postgreschat:
    image: postgres:13
    container_name: postgres_database_chat
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network_chat
  postgrestestchat:
    image: postgres:13
    container_name: postgres_database_chat_test
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=Password.123
    ports:
      - 5436:5432
    networks:
      - my_network_chat
  pgadminWs:
    depends_on:
      - postgreschat
    image: dpage/pgadmin4
    container_name: pgadmin_ws_micro_service
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5051:80
    networks:
      - my_network_chat
networks:
  my_network_chat:
    driver: bridge
volumes:
  postgres_data: